name: fueltric
description: "Aplikasi GIS Penyebaran SPBU & SPKLU di Surabaya"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^10.0.0
  provider: ^6.0.5
  csv: ^5.0.3
  url_launcher: ^6.1.11
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/stations.csv